version: '3'

services:
  app:
    container_name: app
    build: .
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - 3000:3000
      - 6006:6006
    tty: true
    working_dir: /app
